### PR TITLE
Implemented Greetings Workflow

### LINKED ISSUE #3: 🌐 [MISC] - Add workflow for welcoming the contributors
### Description

Create a relevant GitHub workflow for welcoming the contributors on the pull requests and issues. 

For reference, you can follow [this workflow](https://github.com/FahimFBA/assist-me/blob/main/.github/workflows/greetings.yml).

### Related to

Code

### Additional Information

This issue is included in Hacktoberfest. 👏

### PR DESCRIPTION
**Pull request by sharp119**
Hi, 

I've added the Greetings workflow to our repo. Now, when a new contributor opens an issue or PR, they'll get a friendly message from us. 

Please take a look and let me know your thoughts.

closes #3

### CODE REVIEW

**Review by FahimFBA — COMMENTED** [review]
Looks good to me! 👍 
Only the downside is that the Hacktoberfest part might become obsolete after 4/5 days, haha.

Let me know what you think about that. Should we change it or do you want to change it later?

**Comment by sharp119** [comment]
i guess its better to add our own code of conduct docs, I added that cause we dont have it as of now

**Comment by FahimFBA** [comment]
> i guess its better to add our own code of conduct docs, I added that cause we dont have it as of now

Sounds good! In that case, you can create a separate issue and work on that. Additionally, would you be interested in being a maintainer for this repository?

**Comment by sharp119** [comment]
we could do that but i would like you to contiune guiding us through this repo as i too am new in open source so not much familiar with what all things we can do. I got to know about issue template and workflows from issues posted by you.

if assigned maintainer, i would like to bring in more ppl to contribute on this repo so they get started with git and yet i myself will keep contributing as much as i can.

for the code of conduct part i will assign it to someone else

**Comment by sharp119** [comment]
and if the greetings workflow is ok could you merge it ??

**Comment by FahimFBA** [comment]
> we could do that but i would like you to contiune guiding us through this repo as i too am new in open source so not much familiar with what all things we can do. I got to know about issue template and workflows from issues posted by you.
> 
> if assigned maintainer, i would like to bring in more ppl to contribute on this repo so they get started with git and yet i myself will keep contributing as much as i can.
> 
> for the code of conduct part i will assign it to someone else

Sounds good! 👍

**Review by FahimFBA — APPROVED** [review]

**Comment by FahimFBA** [comment]
Also, please try to add `closes #issue_number` in the pull request whenever you open a new pull request. It automatically closes that specific issue whenever the pull request gets accepted.

**Comment by sharp119** [comment]
sure will keep that in mind

**Comment by FahimFBA** [comment]
I have deleted my earlier organization. Adding maintainers is not possible without having an active organization this time. I have sent an invitation to you for an official collaborator for this repository.

But I have a plan to create a new organization pretty soon.

**Pull request merged**
